@echo off
setlocal EnableDelayedExpansion

@REM script is generated by ChatGPT: https://chat.openai.com/share/f008aa0f-a803-4255-9e49-f670721877d7

:: Define the custom character to be added before the dot (change it as desired)
set "custom_character= "

:: Get the value from the clipboard
for /f "tokens=*" %%a in ('powershell -command "Get-Clipboard"') do set "clipboard_value=%%a"

:: Add the custom character before each dot in the value
set "modified_value=!clipboard_value:.=%custom_character%.!"

:: Copy the modified value back to the clipboard
echo !modified_value!| clip

:: Display the modified value
echo Modified value: !modified_value!

endlocal