# style name or JSON path (default "auto")
style: "C:/Users/kevinnitro/AppData/Local/glow/Config/themes/catppuccin-mocha.json"
# show local files only; no network (TUI-mode only)
local: true
# mouse support (TUI-mode only)
mouse: true
# use pager to display markdown
pager: true
# word-wrap at width
width: 80
