#reference from https://github.com/scottmckendry/Windots/blob/main/lazygit/config.yml

notARepository: skip
disableStartupPopups: true

update:
  method: never
  days: 14

gui:
  nerdFontsVersion: '3'
  border: rounded
  mouseEvents: true
  # use catppuccin macchiato yellow - https://github.com/catppuccin/lazygit/blob/main/themes/macchiato/yellow.yml
  theme:
    activeBorderColor:
      - '#eed49f'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#eed49f'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'
  authorColors:
    '*': '#b7bdf8'

git:
  parseEmoji: true
  # paging:
  #   pager: delta --paging=never
  #   colorArg: always

customCommands:
  - key: 'F'
    context: 'localBranches, remoteBranches, remotes'
    command: 'git fetch --prune'
    description: 'Fetch prune branches'
    loadingText: 'Pruning branches'

  - key: 'F'
    context: 'tags'
    command: 'git fetch --prune-tags'
    description: 'Fetch prune tags'
    loadingText: 'Pruning tags'

  - key: 'G'
    context: 'global'
    command: 'git reflog expire --all --expire=now && git gc --prune=now --aggressive'
    description: 'clean up unnecessary files, reflog, optimize'
    prompts:
      - type: 'confirm'
        title: 'Cleanup'
        body: 'Are you sure you want to unnecessary files, reflog, optimize the repo?'
    loadingText: 'Cleaning up'

  - key: 'u'
    context: 'files'
    command: 'git rm --cached {{.SelectedFile.Name | quote}}'
    description: 'Untrack a file'
    prompts:
      - type: 'confirm'
        title: 'Untrack'
        body: 'Are you sure you want to untrack {{.SelectedFile.Name | quote}}?'
    loadingText: 'Untracking file'
