prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: false
      base:
        width: 15
        hidden: false
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: false
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths: {}
theme:
  ui:
    table:
      showSeparator: true
colors:
  text:
    primary: "#CDD6F4"
    secondary: "#A6ADC8"
    inverted: "#313244"
    faint: "#45475A"
    warning: "#F38BA8"
    success: "#A6E3A1"
  background:
    selected: "#9399B2"
  border:
    primary: "#B4BEFE"
    secondary: "#89B4FA"
    faint: "#94E2D5"
pager:
  diff: "delta" # delta | less
